// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexum.Data;

#nullable disable

namespace Nexum.Migrations
{
    [DbContext(typeof(NexumContext))]
    partial class NexumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexum.Models.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb65dac5-8c25-4dff-bd62-0e11cad12f92"),
                            Name = "Portugues",
                            TeacherId = new Guid("6b77e151-c571-49eb-b5c7-73e5f0e13bea")
                        },
                        new
                        {
                            Id = new Guid("914fb3f8-a293-452e-a660-f179693ae440"),
                            Name = "Libras",
                            TeacherId = new Guid("6b77e151-c571-49eb-b5c7-73e5f0e13bea")
                        },
                        new
                        {
                            Id = new Guid("de92fb63-f588-462c-90f3-92dc8e637f2e"),
                            Name = "Matemática",
                            TeacherId = new Guid("f6ebe851-04d7-49cb-9ac1-e750b256da66")
                        },
                        new
                        {
                            Id = new Guid("e237da4d-73eb-4e02-a633-956447bd3783"),
                            Name = "Ingles",
                            TeacherId = new Guid("804e59ba-e3fc-483e-81a6-75ec5e4181b8")
                        },
                        new
                        {
                            Id = new Guid("fe847335-286f-4a36-8516-6c0bb79551fb"),
                            Name = "Ciencias",
                            TeacherId = new Guid("804e59ba-e3fc-483e-81a6-75ec5e4181b8")
                        });
                });

            modelBuilder.Entity("Nexum.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("631b3317-55c6-44fc-af6f-8e78d2102333"),
                            LastName = "Doe",
                            Name = "John",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("21dea7e0-0cff-46dd-83e5-6a57acf5b4fc"),
                            LastName = "Smith",
                            Name = "Jane",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = new Guid("c5fd24da-ce49-4c49-bde8-3918ebb84ab5"),
                            LastName = "Nunes",
                            Name = "Alice",
                            Phone = "555-555-5555"
                        });
                });

            modelBuilder.Entity("Nexum.Models.StudentDiscipline", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("StudentsDisciplines");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("631b3317-55c6-44fc-af6f-8e78d2102333"),
                            DisciplineId = new Guid("bb65dac5-8c25-4dff-bd62-0e11cad12f92")
                        },
                        new
                        {
                            StudentId = new Guid("c5fd24da-ce49-4c49-bde8-3918ebb84ab5"),
                            DisciplineId = new Guid("914fb3f8-a293-452e-a660-f179693ae440")
                        },
                        new
                        {
                            StudentId = new Guid("21dea7e0-0cff-46dd-83e5-6a57acf5b4fc"),
                            DisciplineId = new Guid("de92fb63-f588-462c-90f3-92dc8e637f2e")
                        },
                        new
                        {
                            StudentId = new Guid("c5fd24da-ce49-4c49-bde8-3918ebb84ab5"),
                            DisciplineId = new Guid("e237da4d-73eb-4e02-a633-956447bd3783")
                        },
                        new
                        {
                            StudentId = new Guid("c5fd24da-ce49-4c49-bde8-3918ebb84ab5"),
                            DisciplineId = new Guid("fe847335-286f-4a36-8516-6c0bb79551fb")
                        });
                });

            modelBuilder.Entity("Nexum.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b77e151-c571-49eb-b5c7-73e5f0e13bea"),
                            Name = "Paulo"
                        },
                        new
                        {
                            Id = new Guid("f6ebe851-04d7-49cb-9ac1-e750b256da66"),
                            Name = "Marcos"
                        },
                        new
                        {
                            Id = new Guid("804e59ba-e3fc-483e-81a6-75ec5e4181b8"),
                            Name = "Luiz"
                        });
                });

            modelBuilder.Entity("Nexum.Models.Discipline", b =>
                {
                    b.HasOne("Nexum.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Nexum.Models.StudentDiscipline", b =>
                {
                    b.HasOne("Nexum.Models.Discipline", "Discipline")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexum.Models.Student", "Student")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Nexum.Models.Discipline", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("Nexum.Models.Student", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("Nexum.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
